import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://quantlabusa.dev";
  const lastModified = new Date();

  const corePages: MetadataRoute.Sitemap = [
    { url: `${baseUrl}/`, lastModified, changeFrequency: "weekly", priority: 1.0 },
    { url: `${baseUrl}/about`, lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/about/team`, lastModified, changeFrequency: "monthly", priority: 0.6 },
    { url: `${baseUrl}/services`, lastModified, changeFrequency: "monthly", priority: 0.9 },
    { url: `${baseUrl}/work`, lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: `${baseUrl}/pricing`, lastModified, changeFrequency: "monthly", priority: 0.9 },
    { url: `${baseUrl}/methodology`, lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/process`, lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/security`, lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/certifications-credentials`, lastModified, changeFrequency: "monthly", priority: 0.6 },
    { url: `${baseUrl}/reviews`, lastModified, changeFrequency: "monthly", priority: 0.6 },
    { url: `${baseUrl}/press`, lastModified, changeFrequency: "monthly", priority: 0.5 },
    { url: `${baseUrl}/press-kit`, lastModified, changeFrequency: "monthly", priority: 0.4 },
    { url: `${baseUrl}/newsletter`, lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/newsroom`, lastModified, changeFrequency: "weekly", priority: 0.6 },
    { url: `${baseUrl}/tools`, lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/faq`, lastModified, changeFrequency: "monthly", priority: 0.6 },
    { url: `${baseUrl}/contact`, lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/discovery-call`, lastModified, changeFrequency: "monthly", priority: 0.95 },
    { url: `${baseUrl}/privacy`, lastModified, changeFrequency: "yearly", priority: 0.3 },
    { url: `${baseUrl}/terms`, lastModified, changeFrequency: "yearly", priority: 0.3 },
  ];

  const serviceSlugs = [
    "custom-business-software",
    "custom-crm-development",
    "cloud-infrastructure",
    "web-applications",
    "payments-invoicing-licensing",
    "penetration-testing",
    "mitre-attack-assessment",
    "algorithmic-trading-systems",
    "stripe-integration",
    "license-server",
    "subscription-billing",
    "web-app-pentest",
    "network-pentest",
    "active-directory-pentest",
    "mobile-app-development",
    "api-development",
    "saas-platform-development",
    "devops-engineering",
    "ai-integration-services",
    "ecommerce-development",
    "data-engineering",
    "business-intelligence-dashboards",
    "legacy-system-modernization",
    "mvp-development",
    "technical-due-diligence",
    "fractional-cto-services",
    "cloud-migration",
    "qa-and-test-automation",
    "ai-chatbot-development",
    "saas-security-audit",
    "database-design-and-optimization",
    "third-party-api-integration",
    "managed-security-services",
    "product-design-services",
    "code-audit-services",
    "performance-optimization-services",
  ];

  const servicePages: MetadataRoute.Sitemap = serviceSlugs.map((slug) => ({
    url: `${baseUrl}/services/${slug}`,
    lastModified,
    changeFrequency: "monthly",
    priority: 0.8,
  }));

  const citySlugs = [
    "macon-ga",
    "atlanta-ga",
    "augusta-ga",
    "columbus-ga",
    "savannah-ga",
    "miami-fl",
    "austin-tx",
    "dallas-tx",
    "chicago-il",
    "seattle-wa",
    "new-york-ny",
    "charlotte-nc",
    "nashville-tn",
    "san-francisco-ca",
  ];

  const cityPages: MetadataRoute.Sitemap = citySlugs.map((slug) => ({
    url: `${baseUrl}/software-development-${slug}`,
    lastModified,
    changeFrequency: "monthly",
    priority: 0.8,
  }));

  // Expanded city coverage — these have a top-level landing page only (no
  // city-scoped service sub-pages), so they are kept out of citySlugs to avoid
  // emitting /services/<service>/<city> URLs the [city] route does not generate.
  const expandedCitySlugs = [
    "orlando-fl",
    "tampa-fl",
    "jacksonville-fl",
    "raleigh-nc",
    "charleston-sc",
    "birmingham-al",
    "knoxville-tn",
    "memphis-tn",
    "houston-tx",
    "san-antonio-tx",
    "fort-worth-tx",
    "el-paso-tx",
    "phoenix-az",
    "tucson-az",
    "albuquerque-nm",
    "denver-co",
    "boston-ma",
    "philadelphia-pa",
    "pittsburgh-pa",
    "washington-dc",
    "baltimore-md",
    "newark-nj",
    "providence-ri",
    "buffalo-ny",
    "columbus-oh",
    "cleveland-oh",
    "cincinnati-oh",
    "indianapolis-in",
    "detroit-mi",
    "minneapolis-mn",
    "kansas-city-mo",
    "milwaukee-wi",
    "los-angeles-ca",
    "san-diego-ca",
    "san-jose-ca",
    "sacramento-ca",
    "portland-or",
    "salt-lake-city-ut",
    "las-vegas-nv",
    "boise-id",
  ];

  const expandedCityPages: MetadataRoute.Sitemap = expandedCitySlugs.map((slug) => ({
    url: `${baseUrl}/software-development-${slug}`,
    lastModified,
    changeFrequency: "monthly",
    priority: 0.75,
  }));

  const cityScopedServices = [
    "penetration-testing",
    "custom-crm-development",
    "stripe-integration",
    "mobile-app-development",
    "saas-platform-development",
    "ai-integration-services",
    "web-app-pentest",
    "devops-engineering",
  ];

  const cityScopedServicePages: MetadataRoute.Sitemap = cityScopedServices.flatMap((service) =>
    citySlugs.map((city) => ({
      url: `${baseUrl}/services/${service}/${city}`,
      lastModified,
      changeFrequency: "monthly" as const,
      priority: 0.75,
    }))
  );

  const neighborhoodSlugs = [
    "atlanta-buckhead",
    "atlanta-midtown",
    "atlanta-alpharetta",
    "atlanta-marietta",
    "macon-downtown",
    "macon-bibb-county",
    "austin-downtown",
    "dallas-uptown",
    "miami-brickell",
    "nyc-manhattan",
    "san-francisco-soma",
    "seattle-south-lake-union",
  ];

  const neighborhoodPages: MetadataRoute.Sitemap = [
    { url: `${baseUrl}/locations`, lastModified, changeFrequency: "monthly", priority: 0.7 },
    ...neighborhoodSlugs.map((slug) => ({
      url: `${baseUrl}/locations/${slug}`,
      lastModified,
      changeFrequency: "monthly" as const,
      priority: 0.65,
    })),
  ];

  const industrySlugs = [
    "fintech",
    "construction",
    "insurance",
    "e-commerce",
    "healthcare",
    "legal-services",
    "saas",
    "manufacturing",
    "real-estate",
    "logistics",
    "education",
    "hospitality",
    "nonprofit",
    "professional-services",
    "automotive",
    "energy",
    "agriculture",
    "biotech",
    "telecommunications",
    "media-and-entertainment",
    "travel-and-tourism",
    "government",
    "retail",
    "transportation",
    "gaming",
  ];

  const industryPages: MetadataRoute.Sitemap = industrySlugs.map((slug) => ({
    url: `${baseUrl}/industries/${slug}`,
    lastModified,
    changeFrequency: "monthly",
    priority: 0.7,
  }));

  const versusSlugs = [
    "salesforce",
    "shopify",
    "big-4-pentest",
    "hubspot",
    "toptal",
    "upwork",
    "webflow",
    "wordpress",
    "zoho",
    "pipedrive",
    "netsuite",
    "monday-com",
    "bubble-io",
    "retool",
    "airtable",
    "fiverr",
    "squarespace",
    "wix",
    "freshworks",
    "dynamics-365",
    "clickup",
    "jira",
    "asana",
    "notion",
    "zapier",
    "make",
    "outsystems",
    "mendix",
    "supabase",
    "firebase",
    "heroku",
    "render",
    "quickbase",
  ];

  const versusPages: MetadataRoute.Sitemap = versusSlugs.map((slug) => ({
    url: `${baseUrl}/vs/${slug}`,
    lastModified,
    changeFrequency: "monthly",
    priority: 0.7,
  }));

  const caseStudySlugs = [
    "northcrest-fence",
    "hobbspeak",
    "bridgepointe-painting",
    "protectwithbri",
    "j5-sales-os",
    "wilder-recovery",
    "regional-medical-billing",
    "coastal-yacht-services",
    "northstar-trading-desk",
    "clear-channel-broadcast",
  ];

  const caseStudyPages: MetadataRoute.Sitemap = caseStudySlugs.map((slug) => ({
    url: `${baseUrl}/work/${slug}`,
    lastModified,
    changeFrequency: "monthly",
    priority: 0.7,
  }));

  const calculatorSlugs = [
    "stripe-cost",
    "crm-roi",
    "pentest-cost",
    "build-vs-buy",
    "saas-pricing-calculator",
    "downtime-cost-calculator",
    "technical-debt-calculator",
    "cloud-hosting-cost-calculator",
    "developer-salary-vs-agency-calculator",
    "saas-ltv-cac-calculator",
  ];

  const calculatorPages: MetadataRoute.Sitemap = calculatorSlugs.map((slug) => ({
    url: `${baseUrl}/calculators/${slug}`,
    lastModified,
    changeFrequency: "monthly",
    priority: 0.7,
  }));

  const resourceSlugs = [
    "build-vs-buy-playbook",
    "web-app-pentest-checklist",
    "crm-rollout-playbook",
    "mvp-to-prod-playbook",
    "stripe-integration-checklist",
    "mitre-attack-worksheet",
    "llc-vs-c-corp-decision-checklist",
    "stripe-connect-marketplace-onboarding-template",
    "mitre-attack-maturity-self-assessment-v2",
    "custom-crm-rfp-template-2026",
    "internal-tools-build-vs-buy-worksheet",
    "technical-due-diligence-checklist",
    "saas-launch-checklist",
    "vendor-security-questionnaire-template",
    "software-project-estimate-worksheet",
    "incident-response-plan-template",
    "api-design-guidelines-checklist",
    "saas-security-checklist",
    "database-backup-and-recovery-plan-template",
    "api-integration-requirements-template",
    "penetration-test-rfp-template",
    "cloud-cost-optimization-checklist",
    "code-review-checklist",
  ];

  const resourcePages: MetadataRoute.Sitemap = [
    { url: `${baseUrl}/resources`, lastModified, changeFrequency: "monthly", priority: 0.7 },
    ...resourceSlugs.map((slug) => ({
      url: `${baseUrl}/resources/${slug}`,
      lastModified,
      changeFrequency: "monthly" as const,
      priority: 0.65,
    })),
  ];

  const blogSlugs = [
    "custom-crm-development-guide",
    "build-vs-buy-software-2026",
    "what-is-penetration-testing",
    "atlanta-software-development-guide-2026",
    "what-is-mitre-attack-framework",
    "nextjs-stripe-integration-guide",
    "custom-crm-vs-salesforce-vs-hubspot-2026",
    "best-custom-software-development-companies-atlanta-2026",
    "best-penetration-testing-companies-georgia-2026",
    "how-to-choose-a-software-development-company-checklist",
    "penetration-test-cost-2026",
    "crm-migration-from-salesforce-checklist",
    "soc2-pentest-prep-guide-2026",
    "stripe-connect-marketplace-architecture",
    "building-multi-tenant-saas-postgres-rls",
    "internal-tools-platform-engineering-guide",
    "hire-fractional-cto-vs-software-firm",
    "cybersecurity-services-for-saas-startups-2026",
    "dedicated-development-team-vs-agency",
    "what-is-a-pen-test-vs-vulnerability-scan",
    "2026-state-of-custom-software-development",
    "nextjs-vs-remix-vs-sveltekit-2026",
    "custom-internal-tools-vs-retool-2026",
    "pci-dss-compliance-saas-checklist",
    "hipaa-compliant-saas-architecture",
    "red-team-vs-pen-test-vs-audit",
    "stripe-webhook-security-best-practices",
    "custom-software-rfp-template-2026",
    "software-development-contract-redlines",
    "crm-data-migration-from-spreadsheets",
    "vcs-vcio-vs-software-development-firm",
    "custom-crm-for-real-estate-teams-2026",
    "salesforce-alternatives-for-small-business-2026",
    "spreadsheet-to-web-app-migration-guide",
    "internal-tools-vs-custom-software-2026",
    "stripe-vs-paddle-vs-lemon-squeezy-2026",
    "handling-failed-payments-in-stripe",
    "saas-pricing-models-explained-2026",
    "subscription-billing-system-architecture",
    "penetration-testing-for-fintech-startups-2026",
    "owasp-top-10-explained-2026",
    "how-to-prepare-for-a-soc-2-audit-2026",
    "api-security-best-practices-2026",
    "nextjs-16-app-router-guide-2026",
    "server-components-vs-client-components-explained",
    "postgres-vs-mysql-for-saas-2026",
    "scaling-a-saas-database-guide-2026",
    "soc-2-vs-iso-27001-2026",
    "gdpr-for-us-saas-companies-2026",
    "hipaa-compliance-checklist-for-startups-2026",
    "ccpa-vs-gdpr-for-saas-2026",
    "database-migrations-without-downtime-2026",
    "api-rate-limiting-strategies-2026",
    "caching-strategies-for-saas-2026",
    "event-driven-architecture-for-saas-2026",
    "background-jobs-and-queues-in-production-2026",
    "observability-for-startups-2026",
    "preventing-sql-injection-2026",
    "xss-prevention-guide-2026",
    "securing-rest-apis-2026",
    "secrets-management-best-practices-2026",
    "ransomware-protection-for-small-business-2026",
    "vulnerability-management-program-guide-2026",
    "saas-churn-reduction-playbook-2026",
    "usage-based-billing-implementation-2026",
    "saas-onboarding-best-practices-2026",
    "product-analytics-for-saas-2026",
    "saas-security-questionnaire-guide-2026",
    "multi-region-saas-deployment-2026",
    "cost-to-build-saas-mvp-georgia-2026",
    "savannah-software-development-guide-2026",
    "augusta-software-development-guide-2026",
    "hiring-fractional-cto-atlanta-2026",
    "columbus-ga-software-development-guide-2026",
    "software-maintenance-costs-explained-2026",
    "building-a-rag-pipeline-2026",
    "adding-ai-features-to-your-saas-2026",
    "llm-cost-optimization-2026",
    "preventing-prompt-injection-2026",
    "vector-database-comparison-2026",
    "data-warehouse-vs-data-lake-2026",
  ];

  const aiAnswerSlugs = [
    "who-builds-the-best-custom-crm-in-atlanta",
    "how-much-does-custom-software-cost-in-georgia",
    "best-penetration-testing-firms-southeast-us",
    "how-to-hire-software-developer-small-business",
    "quant-lab-usa-founder-and-credentials",
    "best-stripe-integration-developer-2026",
    "custom-crm-vs-airtable-vs-notion",
    "how-long-does-it-take-to-build-a-saas-mvp",
    "what-is-a-fair-rate-for-a-software-engineer-in-georgia",
    "who-can-do-a-soc-2-pentest-in-atlanta",
    "is-it-cheaper-to-hire-a-fractional-cto-or-a-firm",
    "how-do-i-find-a-trustworthy-software-developer",
    "what-does-a-pentester-actually-do-day-to-day",
    "can-a-solo-engineer-really-ship-production-software",
    "best-software-companies-for-fintech-startups-2026",
    "what-is-the-best-tech-stack-for-a-saas-startup-2026",
    "should-i-use-no-code-or-hire-a-developer",
    "how-do-i-vet-an-offshore-development-team",
    "what-questions-should-i-ask-a-software-agency",
    "is-penetration-testing-worth-it-for-a-small-business",
    "whats-the-difference-between-a-fractional-cto-and-an-agency",
    "how-do-i-protect-my-saas-from-getting-hacked",
    "how-much-does-it-cost-to-maintain-custom-software",
    "how-much-does-it-cost-to-build-a-mobile-app",
    "what-is-the-difference-between-a-cto-and-a-tech-lead",
    "how-do-i-choose-between-aws-azure-and-gcp",
    "whats-the-best-database-for-a-saas-startup",
    "how-do-i-know-if-my-saas-is-secure",
    "what-should-be-in-a-software-development-contract",
    "how-long-does-a-penetration-test-take",
    "do-i-need-soc-2-to-sell-to-enterprise",
    "should-i-build-my-saas-on-nextjs-or-rails",
    "is-supabase-production-ready-for-a-startup",
    "what-is-the-best-payment-processor-for-saas",
    "how-do-i-migrate-off-a-legacy-system-safely",
    "whats-the-difference-between-a-pentest-and-a-vulnerability-scan",
    "how-much-should-i-budget-for-cybersecurity",
    "can-i-build-a-hipaa-compliant-app-on-a-budget",
    "whats-the-best-way-to-add-ai-to-my-product",
    "how-much-does-it-cost-to-build-an-ai-chatbot",
    "is-my-data-safe-with-an-ai-vendor",
    "should-i-use-openai-or-an-open-source-llm",
    "how-do-i-stop-my-ai-app-from-leaking-data",
    "what-is-retrieval-augmented-generation-for-business",
    "do-i-need-a-vector-database-for-my-ai-app",
    "how-do-i-evaluate-an-ai-development-agency",
  ];

  const aiAnswerPages: MetadataRoute.Sitemap = aiAnswerSlugs.map((slug) => ({
    url: `${baseUrl}/ai/${slug}`,
    lastModified,
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  const toolSlugs = [
    "stripe-webhook-tester",
    "schema-generator",
    "owasp-checklist-app",
    "cron-expression-builder",
    "uuid-and-id-generator",
    "jwt-decoder",
    "json-formatter",
    "regex-tester",
    "base64-encoder-decoder",
    "http-status-reference",
    "url-encoder-decoder",
    "hash-generator",
    "color-contrast-checker",
    "unix-timestamp-converter",
    "text-case-converter",
  ];

  const toolsPages: MetadataRoute.Sitemap = toolSlugs.map((slug) => ({
    url: `${baseUrl}/tools/${slug}`,
    lastModified,
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  const pressReleaseSlugs = [
    "quant-lab-usa-launches-custom-software-and-cybersecurity-firm-in-macon-ga",
    "quant-lab-usa-publishes-2026-software-development-cost-guide",
    "quant-lab-usa-completes-14-client-engagements-2026",
    "quant-lab-usa-now-serving-14-us-cities-with-remote-software-development",
    "quant-lab-usa-releases-free-developer-tools-suite-for-stripe-owasp-schema",
  ];

  const newsroomPages: MetadataRoute.Sitemap = pressReleaseSlugs.map((slug) => ({
    url: `${baseUrl}/newsroom/${slug}`,
    lastModified,
    changeFrequency: "monthly" as const,
    priority: 0.55,
  }));

  const blogPages: MetadataRoute.Sitemap = [
    { url: `${baseUrl}/blog`, lastModified, changeFrequency: "weekly", priority: 0.8 },
    ...blogSlugs.map((slug) => ({
      url: `${baseUrl}/blog/${slug}`,
      lastModified,
      changeFrequency: "monthly" as const,
      priority: slug === "custom-crm-development-guide" ? 0.9 : 0.7,
    })),
  ];

  const glossarySlugs = [
    "what-is-a-crm",
    "what-is-saas",
    "what-is-an-mvp",
    "what-is-an-api",
    "what-is-nextjs",
    "what-is-server-side-rendering",
    "what-is-jamstack",
    "what-is-webhooks",
    "what-is-rest-vs-graphql",
    "what-is-multi-tenant-saas",
    "what-is-penetration-testing",
    "what-is-owasp-top-10",
    "what-is-mitre-attack",
    "what-is-soc-2",
    "what-is-pci-dss",
    "what-is-hipaa-compliance",
    "what-is-active-directory",
    "what-is-a-red-team",
    "what-is-zero-trust",
    "what-is-a-web-app-firewall",
    "what-is-a-tech-stack",
    "what-is-product-led-growth",
    "what-is-a-data-warehouse",
    "what-is-event-sourcing",
    "what-is-cqrs",
    "what-is-domain-driven-design",
    "what-is-microservices-architecture",
    "what-is-a-monorepo",
    "what-is-feature-flagging",
    "what-is-blue-green-deployment",
    "what-is-zero-knowledge-architecture",
    "what-is-an-soc-2-report",
    "what-is-fido2",
    "what-is-passkey-authentication",
    "what-is-an-iam",
    "what-is-saml-sso",
    "what-is-oauth2",
    "what-is-an-jwt",
    "what-is-zero-trust-network-access",
    "what-is-secrets-management",
    "what-is-a-vulnerability",
    "what-is-a-cve",
    "what-is-threat-modeling",
    "what-is-a-security-operations-center",
    "what-is-siem",
    "what-is-edr",
    "what-is-multi-factor-authentication",
    "what-is-encryption-at-rest",
    "what-is-tls",
    "what-is-phishing",
    "what-is-ci-cd",
    "what-is-docker",
    "what-is-kubernetes",
    "what-is-serverless",
    "what-is-a-load-balancer",
    "what-is-a-cdn",
    "what-is-database-indexing",
    "what-is-an-orm",
    "what-is-a-message-queue",
    "what-is-idempotency",
    "what-is-mrr",
    "what-is-arr",
    "what-is-customer-churn",
    "what-is-customer-acquisition-cost",
    "what-is-customer-lifetime-value",
    "what-is-product-market-fit",
    "what-is-agile",
    "what-is-scrum",
    "what-is-technical-debt",
    "what-is-a-design-sprint",
    "what-is-graphql",
    "what-is-grpc",
    "what-are-websockets",
    "what-is-an-api-gateway",
    "what-is-a-service-mesh",
    "what-is-rate-limiting",
    "what-is-a-rest-api",
    "what-is-openapi",
    "what-is-api-versioning",
    "what-is-long-polling",
    "what-is-infrastructure-as-code",
    "what-is-terraform",
    "what-is-observability",
    "what-is-distributed-tracing",
    "what-is-a-vpc",
    "what-is-redis",
    "what-is-database-sharding",
    "what-is-caching",
    "what-is-load-testing",
    "what-is-chaos-engineering",
    "what-is-sql-injection",
    "what-is-cross-site-scripting",
    "what-is-csrf",
    "what-is-a-ddos-attack",
    "what-is-ransomware",
    "what-is-a-zero-day-exploit",
    "what-is-social-engineering",
    "what-is-a-supply-chain-attack",
    "what-is-credential-stuffing",
    "what-is-privilege-escalation",
    "what-is-rbac",
    "what-is-abac",
    "what-is-public-key-infrastructure",
    "what-is-hashing",
    "what-is-dns",
    "what-is-devsecops",
    "what-is-vulnerability-scanning",
    "what-is-patch-management",
    "what-is-the-secure-sdlc",
    "what-is-a-man-in-the-middle-attack",
    "what-is-a-vector-database",
    "what-is-retrieval-augmented-generation",
    "what-is-an-llm",
    "what-is-prompt-injection",
    "what-is-fine-tuning",
    "what-is-an-embedding",
    "what-is-mlops",
    "what-is-a-data-lake",
    "what-is-etl",
    "what-is-a-feature-store",
  ];

  const glossaryPages: MetadataRoute.Sitemap = [
    { url: `${baseUrl}/glossary`, lastModified, changeFrequency: "monthly", priority: 0.6 },
    ...glossarySlugs.map((slug) => ({
      url: `${baseUrl}/glossary/${slug}`,
      lastModified,
      changeFrequency: "monthly" as const,
      priority: 0.55,
    })),
  ];

  return [
    ...corePages,
    ...servicePages,
    ...cityPages,
    ...expandedCityPages,
    ...cityScopedServicePages,
    ...neighborhoodPages,
    ...industryPages,
    ...versusPages,
    ...caseStudyPages,
    ...calculatorPages,
    ...resourcePages,
    ...blogPages,
    ...glossaryPages,
    ...aiAnswerPages,
    ...toolsPages,
    ...newsroomPages,
  ];
}
