import type { Metadata } from "next";
import Link from "next/link";
import { BookOpen, CheckCircle2, Pencil, ShieldAlert, Users2 } from "lucide-react";
import { pageMetadata } from "@/lib/seoMeta";
import { ConsultationCTA } from "@/components/ConsultationCTA";

export const metadata: Metadata = pageMetadata({
    title: "Editorial Policy & Sourcing Standards (2026) | QUANT LAB USA",
    description:
        "How QUANT LAB USA writes, sources, and verifies every article — including AI disclosure, citation standards, and corrections policy. Updated for 2026.",
    slug: "about/editorial-policy",
});

const lastUpdated = "2026-05-16";

const policyLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: "Editorial Policy | QUANT LAB USA",
    url: "https://quantlabusa.dev/about/editorial-policy",
    dateModified: lastUpdated,
    publisher: { "@id": "https://quantlabusa.dev/#organization" },
    isPartOf: { "@id": "https://quantlabusa.dev/#website" },
    about: {
        "@type": "Thing",
        name: "Editorial standards and authorship policy",
    },
};

const principles = [
    {
        icon: Users2,
        title: "Named authors only",
        body: "Every long-form post on this site is attributed to a real, named author with a /authors/<slug> bio. We do not publish ghostwritten or AI-generated bylines, and we do not buy guest posts from link-builders.",
    },
    {
        icon: Pencil,
        title: "Written from inside the work",
        body: "Posts come out of live engagements — quotes we have received or sent, code we have shipped, pentests we have run. When we cite a number, range, or methodology, it reflects work we have done or are doing.",
    },
    {
        icon: BookOpen,
        title: "Cite authoritative sources",
        body: "Any claim that is not common knowledge gets an inline citation to a primary source. We prefer .gov, .edu, peer-reviewed material, official vendor documentation, and standards bodies (OWASP, NIST, MITRE, CISA) over secondary blog posts.",
    },
    {
        icon: CheckCircle2,
        title: "Editorial review before publish",
        body: "Every post is reviewed by at least one additional engineer or security practitioner on staff before publish. Reviewers check technical accuracy, citation integrity, and whether the conclusion actually follows from the evidence.",
    },
    {
        icon: ShieldAlert,
        title: "Corrections are public and dated",
        body: "When we get something wrong — a number, a name, a methodology — we update the post in place, add a dated correction note at the bottom, and re-issue the modifiedTime in the article schema. We do not silently delete or rewrite errors.",
    },
];

const editorialProcess = [
    {
        step: "1. Draft",
        body: "An author writes the post from a working knowledge of the topic. Quotes from live work are anonymized only when client confidentiality requires it.",
    },
    {
        step: "2. Source pass",
        body: "Every factual claim that is not common engineering knowledge is annotated with a citation candidate. The author finds the highest-authority primary source available and links inline.",
    },
    {
        step: "3. Technical review",
        body: "A second engineer or security practitioner on staff reviews the post for accuracy, validates citations, and challenges weak conclusions.",
    },
    {
        step: "4. Copy & schema",
        body: "Final pass on copy, byline, dates, reading-time estimate, JSON-LD Article and Person schema, and the editorial footer.",
    },
    {
        step: "5. Publish & monitor",
        body: "Post goes live. We monitor for reader feedback at beltz@quantlabusa.dev and update the post (with a dated correction note) when needed.",
    },
];

export default function EditorialPolicyPage() {
    return (
        <main className="min-h-screen bg-quant-bg text-quant-text pt-28 pb-24">
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(policyLd) }}
            />

            <div className="container mx-auto px-6 max-w-3xl">
                <nav aria-label="Breadcrumb" className="mb-8">
                    <ol className="flex items-center gap-2 text-xs text-gray-400">
                        <li>
                            <Link href="/" className="hover:text-sky-400 transition-colors">
                                Home
                            </Link>
                        </li>
                        <li aria-hidden="true" className="text-gray-700">
                            ›
                        </li>
                        <li>
                            <Link
                                href="/about"
                                className="hover:text-sky-400 transition-colors"
                            >
                                About
                            </Link>
                        </li>
                        <li aria-hidden="true" className="text-gray-700">
                            ›
                        </li>
                        <li className="text-gray-300">Editorial policy</li>
                    </ol>
                </nav>

                <header className="mb-10">
                    <span className="inline-block text-quant-blue text-sm font-semibold tracking-[0.2em] uppercase mb-5">
                        Editorial Policy
                    </span>
                    <h1 className="text-4xl md:text-5xl font-bold text-white leading-tight mb-5">
                        How we write, source, and correct published content
                    </h1>
                    <p className="text-gray-400 text-lg leading-relaxed">
                        This is the working policy for everything published under
                        the QUANT LAB USA brand — blog posts, case studies, service
                        pages, and city pages. It is also the standard our reviewers
                        hold every draft against before publish.
                    </p>
                    <p className="mt-3 text-xs text-gray-500">
                        Last updated:{" "}
                        <time dateTime={lastUpdated}>{lastUpdated}</time>
                    </p>
                </header>

                <section className="mb-12">
                    <h2 className="text-2xl md:text-3xl font-bold text-white mb-6">
                        Principles
                    </h2>
                    <div className="grid grid-cols-1 gap-4">
                        {principles.map((p) => {
                            const Icon = p.icon;
                            return (
                                <div
                                    key={p.title}
                                    className="rounded-2xl border border-white/8 bg-[#0d1526]/60 p-6"
                                >
                                    <h3 className="flex items-center gap-2 text-lg font-semibold text-white mb-2">
                                        <Icon className="h-5 w-5 text-sky-400" />
                                        {p.title}
                                    </h3>
                                    <p className="text-gray-400 leading-relaxed">{p.body}</p>
                                </div>
                            );
                        })}
                    </div>
                </section>

                <section className="mb-12">
                    <h2 className="text-2xl md:text-3xl font-bold text-white mb-6">
                        The 5-step editorial process
                    </h2>
                    <ol className="space-y-4">
                        {editorialProcess.map((p) => (
                            <li
                                key={p.step}
                                className="rounded-xl border border-white/8 bg-[#0d1526]/40 p-5"
                            >
                                <p className="text-sm font-semibold text-sky-400 mb-2">
                                    {p.step}
                                </p>
                                <p className="text-gray-300 leading-relaxed">{p.body}</p>
                            </li>
                        ))}
                    </ol>
                </section>

                <section className="mb-12">
                    <h2 className="text-2xl md:text-3xl font-bold text-white mb-4">
                        AI usage disclosure
                    </h2>
                    <p className="text-gray-400 leading-relaxed mb-3">
                        We use AI tooling (Claude, GitHub Copilot, ChatGPT) the same
                        way a working engineer uses any IDE plugin — for drafting,
                        rewording, and surfacing relevant references. AI-generated
                        prose is always reviewed, edited, and signed off by a named
                        human author before publish. We do not autopublish AI output
                        under a real byline, and we do not invent author personas.
                    </p>
                    <p className="text-gray-400 leading-relaxed">
                        Where a post or section is materially the result of AI
                        synthesis (e.g. a large summary of public benchmarks), we
                        disclose it inline.
                    </p>
                </section>

                <section className="mb-12">
                    <h2 className="text-2xl md:text-3xl font-bold text-white mb-4">
                        Sponsorship, advertising, and affiliate disclosure
                    </h2>
                    <p className="text-gray-400 leading-relaxed mb-3">
                        QUANT LAB USA does not run paid advertising on the blog and
                        does not accept sponsored posts. Tooling and vendors
                        mentioned in posts (Next.js, Stripe, Vercel, Postgres,
                        Resend, Sentry, etc.) appear because we use them in client
                        builds, not because of any commercial relationship.
                    </p>
                    <p className="text-gray-400 leading-relaxed">
                        Where an affiliate or referral arrangement exists, the post
                        will say so inline. As of the last-updated date above, no
                        such arrangements are active.
                    </p>
                </section>

                <section className="mb-12">
                    <h2 className="text-2xl md:text-3xl font-bold text-white mb-4">
                        Conflicts of interest
                    </h2>
                    <p className="text-gray-400 leading-relaxed">
                        QUANT LAB USA INC is a software and security services firm.
                        Posts that recommend buying or building a system are written
                        with the obvious caveat that we sell those services. We try
                        to declare it openly — if a post points you at our service
                        page, it is also pointing you at a billable engagement. When
                        the honest answer is &quot;you don&apos;t need us,&quot; we
                        say so directly.
                    </p>
                </section>

                <section className="mb-12">
                    <h2 className="text-2xl md:text-3xl font-bold text-white mb-4">
                        Corrections &amp; takedown requests
                    </h2>
                    <p className="text-gray-400 leading-relaxed mb-3">
                        See something wrong? Email{" "}
                        <a
                            href="mailto:beltz@quantlabusa.dev?subject=Editorial%20correction"
                            className="text-sky-400 hover:underline"
                        >
                            beltz@quantlabusa.dev
                        </a>{" "}
                        with the URL and the issue. We respond to genuine correction
                        requests within five business days and update the post in
                        place with a dated correction note at the bottom.
                    </p>
                    <p className="text-gray-400 leading-relaxed">
                        For full takedown requests (e.g. a former client wants their
                        name removed from a case study), see the contact line
                        above — we generally honor reasonable requests.
                    </p>
                </section>

                <section className="rounded-2xl border border-white/10 bg-gradient-to-br from-[#0d1526] to-[#0a1120] p-10 text-center">
                    <h2 className="text-2xl font-bold text-white mb-3">
                        Read about the team
                    </h2>
                    <p className="text-gray-400 max-w-xl mx-auto mb-6 leading-relaxed">
                        Bios, credentials, and expertise areas for every author who
                        publishes on this site.
                    </p>
                    <div className="flex flex-wrap items-center justify-center gap-3">
                        <Link
                            href="/authors"
                            className="inline-flex items-center justify-center px-6 py-3 rounded-full text-sm font-medium border border-white/10 text-gray-200 hover:bg-white/5"
                        >
                            See authors
                        </Link>
                        <Link
                            href="/about/fact-checking"
                            className="inline-flex items-center justify-center px-6 py-3 rounded-full text-sm font-medium border border-white/10 text-gray-200 hover:bg-white/5"
                        >
                            Fact-checking policy
                        </Link>
                        <ConsultationCTA
                            label="Book a Consultation"
                            source="editorial-policy"
                        />
                    </div>
                </section>
            </div>
        </main>
    );
}
