import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, MapPin, UserSquare2 } from "lucide-react";
import { AUTHORS, authorUrl } from "@/lib/authors";
import { pageMetadata } from "@/lib/seoMeta";

export const metadata: Metadata = pageMetadata({
    title: "Authors & Editorial Team 2026 | QUANT LAB USA",
    description:
        "Meet the QUANT LAB USA engineering & editorial team behind every guide and blog post — bios, credentials, and topic expertise. Founder-led, US-based.",
    slug: "authors",
});

const collectionSchema = {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: "QUANT LAB USA Authors & Editorial Team",
    url: "https://quantlabusa.dev/authors",
    isPartOf: { "@id": "https://quantlabusa.dev/#website" },
    about: AUTHORS.map((a) => ({
        "@type": a.isEditorialEntity ? "Organization" : "Person",
        "@id": authorUrl(a.slug),
        name: a.name,
    })),
};

export default function AuthorsIndexPage() {
    return (
        <main className="min-h-screen bg-quant-bg text-quant-text pt-28 pb-24">
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(collectionSchema) }}
            />

            <div className="container mx-auto px-6 max-w-5xl">
                <nav aria-label="Breadcrumb" className="mb-8">
                    <ol className="flex items-center gap-2 text-xs text-gray-400">
                        <li>
                            <Link href="/" className="hover:text-sky-400 transition-colors">
                                Home
                            </Link>
                        </li>
                        <li aria-hidden="true" className="text-gray-700">
                            ›
                        </li>
                        <li className="text-gray-300">Authors</li>
                    </ol>
                </nav>

                <header className="mb-12">
                    <span className="inline-block text-quant-blue text-sm font-semibold tracking-[0.2em] uppercase mb-5">
                        Authors & Editorial Team
                    </span>
                    <h1 className="text-4xl md:text-5xl font-bold leading-tight text-white mb-6">
                        Real people. Real bylines.
                    </h1>
                    <p className="text-lg text-gray-400 leading-relaxed max-w-2xl">
                        Every long-form post on this site is attributed to a named
                        author and reviewed by the editorial team. We do not use
                        ghostwriters and we do not publish AI-generated bylines.
                        Read about our{" "}
                        <Link
                            href="/about/editorial-policy"
                            className="text-sky-400 hover:underline"
                        >
                            editorial policy
                        </Link>{" "}
                        and{" "}
                        <Link
                            href="/about/fact-checking"
                            className="text-sky-400 hover:underline"
                        >
                            fact-checking process
                        </Link>
                        .
                    </p>
                </header>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {AUTHORS.map((author) => (
                        <Link
                            key={author.slug}
                            href={authorUrl(author.slug)}
                            className="group flex h-full flex-col rounded-2xl border border-white/8 bg-[#0d1526]/80 p-6 transition-colors hover:border-sky-400/40"
                        >
                            <div className="flex items-start gap-4">
                                {author.imagePath ? (
                                    <div className="relative h-16 w-16 flex-shrink-0 overflow-hidden rounded-full border border-white/10">
                                        <Image
                                            src={author.imagePath}
                                            alt={`${author.name}, ${author.role}`}
                                            fill
                                            sizes="64px"
                                            className="object-cover"
                                        />
                                    </div>
                                ) : (
                                    <div className="flex h-16 w-16 flex-shrink-0 items-center justify-center rounded-full border border-white/10 bg-white/5">
                                        <UserSquare2 className="h-7 w-7 text-sky-400" />
                                    </div>
                                )}
                                <div className="flex-1">
                                    <h2 className="text-xl font-bold text-white group-hover:text-sky-100">
                                        {author.name}
                                    </h2>
                                    <p className="text-sm text-sky-400">{author.role}</p>
                                    {author.location ? (
                                        <p className="mt-1 inline-flex items-center gap-1 text-xs text-gray-500">
                                            <MapPin className="h-3 w-3" />
                                            {author.location}
                                        </p>
                                    ) : null}
                                </div>
                            </div>
                            {author.tagline ? (
                                <p className="mt-4 text-sm text-gray-400 leading-relaxed">
                                    {author.tagline}
                                </p>
                            ) : null}
                            <span className="mt-4 inline-flex items-center gap-1 text-xs font-medium text-sky-400">
                                Full bio
                                <ArrowRight className="h-3 w-3 transition-transform group-hover:translate-x-0.5" />
                            </span>
                        </Link>
                    ))}
                </div>
            </div>
        </main>
    );
}
